export const CATEGORIES = [
  { id: 1, name: 'Електроніка' },
  { id: 2, name: 'Одяг' },
  { id: 3, name: 'Їжа' },
  { id: 4, name: 'Спорт' },
  { id: 5, name: 'Інше' },
];

export const COUNTRIES_LIST = [
  { code: 'UA', name: 'Україна', flag: '🇺🇦', dialCode: '+380' },
  { code: 'PL', name: 'Польща', flag: '🇵🇱', dialCode: '+48' },
  { code: 'DE', name: 'Німеччина', flag: '🇩🇪', dialCode: '+49' },
  { code: 'US', name: 'США', flag: '🇺🇸', dialCode: '+1' },
  { code: 'CA', name: 'Канада', flag: '🇨🇦', dialCode: '+1' },
  { code: 'GB', name: 'Велика Британія', flag: '🇬🇧', dialCode: '+44' },
  { code: 'FR', name: 'Франція', flag: '🇫🇷', dialCode: '+33' },
  { code: 'IT', name: 'Італія', flag: '🇮🇹', dialCode: '+39' },
  { code: 'ES', name: 'Іспанія', flag: '🇪🇸', dialCode: '+34' },
  { code: 'CZ', name: 'Чехія', flag: '🇨🇿', dialCode: '+420' },
  { code: 'SK', name: 'Словаччина', flag: '🇸🇰', dialCode: '+421' },
  { code: 'HU', name: 'Угорщина', flag: '🇭🇺', dialCode: '+36' },
  { code: 'RO', name: 'Румунія', flag: '🇷🇴', dialCode: '+40' },
  { code: 'MD', name: 'Молдова', flag: '🇲🇩', dialCode: '+373' },
  { code: 'TR', name: 'Туреччина', flag: '🇹🇷', dialCode: '+90' },
  { code: 'NL', name: 'Нідерланди', flag: '🇳🇱', dialCode: '+31' },
  { code: 'BE', name: 'Бельгія', flag: '🇧🇪', dialCode: '+32' },
  { code: 'AT', name: 'Австрія', flag: '🇦🇹', dialCode: '+43' },
  { code: 'CH', name: 'Швейцарія', flag: '🇨🇭', dialCode: '+41' },
  { code: 'PT', name: 'Португалія', flag: '🇵🇹', dialCode: '+351' },
  { code: 'SE', name: 'Швеція', flag: '🇸🇪', dialCode: '+46' },
  { code: 'NO', name: 'Норвегія', flag: '🇳🇴', dialCode: '+47' },
  { code: 'DK', name: 'Данія', flag: '🇩🇰', dialCode: '+45' },
  { code: 'FI', name: 'Фінляндія', flag: '🇫🇮', dialCode: '+358' },
  { code: 'IE', name: 'Ірландія', flag: '🇮🇪', dialCode: '+353' },
  { code: 'GR', name: 'Греція', flag: '🇬🇷', dialCode: '+30' },
  { code: 'BG', name: 'Болгарія', flag: '🇧🇬', dialCode: '+359' },
  { code: 'HR', name: 'Хорватія', flag: '🇭🇷', dialCode: '+385' },
  { code: 'LT', name: 'Литва', flag: '🇱🇹', dialCode: '+370' },
  { code: 'LV', name: 'Латвія', flag: '🇱🇻', dialCode: '+371' },
  { code: 'EE', name: 'Естонія', flag: '🇪🇪', dialCode: '+372' },
  { code: 'GE', name: 'Грузія', flag: '🇬🇪', dialCode: '+995' },
  { code: 'IL', name: 'Ізраїль', flag: '🇮🇱', dialCode: '+972' },
  { code: 'JP', name: 'Японія', flag: '🇯🇵', dialCode: '+81' },
  { code: 'CN', name: 'Китай', flag: '🇨🇳', dialCode: '+86' },
  { code: 'AU', name: 'Австралія', flag: '🇦🇺', dialCode: '+61' },
];